// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYENDaiwkvRC5TKfaO8CPbRCjfccgG_wo',
    appId: '1:413638600877:web:fdf79beeb70b06b5f47e24',
    messagingSenderId: '413638600877',
    projectId: 'hotel-booking-app-3b555',
    authDomain: 'hotel-booking-app-3b555.firebaseapp.com',
    storageBucket: 'hotel-booking-app-3b555.firebasestorage.app',
    measurementId: 'G-7Q5WNXD64S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANVTtHg72iejvDItEFxbVeaElohPQ_WmA',
    appId: '1:413638600877:android:900c880534b70ff3f47e24',
    messagingSenderId: '413638600877',
    projectId: 'hotel-booking-app-3b555',
    storageBucket: 'hotel-booking-app-3b555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIWu3IQNGeSIbb-vW8sWrPVm9HjURXZg',
    appId: '1:413638600877:ios:42cfa04df7a55bc7f47e24',
    messagingSenderId: '413638600877',
    projectId: 'hotel-booking-app-3b555',
    storageBucket: 'hotel-booking-app-3b555.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIWu3IQNGeSIbb-vW8sWrPVm9HjURXZg',
    appId: '1:413638600877:ios:42cfa04df7a55bc7f47e24',
    messagingSenderId: '413638600877',
    projectId: 'hotel-booking-app-3b555',
    storageBucket: 'hotel-booking-app-3b555.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYENDaiwkvRC5TKfaO8CPbRCjfccgG_wo',
    appId: '1:413638600877:web:63f46e4a9d742078f47e24',
    messagingSenderId: '413638600877',
    projectId: 'hotel-booking-app-3b555',
    authDomain: 'hotel-booking-app-3b555.firebaseapp.com',
    storageBucket: 'hotel-booking-app-3b555.firebasestorage.app',
    measurementId: 'G-427QSFQNKP',
  );
}
